repos:
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      args:
        - --config=.code_quality/.flake8
-   repo: https://github.com/pycqa/pylint
    rev: v2.15.9
    hooks:
    - id: pylint
      args:
      - --rcfile=.code_quality/.pylintrc
-   repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
    - id: black
      language_version: python3
      args:
          - --config
          - .code_quality/pyproject_black.toml
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        args:
          - -c
          - .code_quality/bandit.yaml
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
    -   id: mypy
        args:
          - --config-file=.code_quality/mypy.ini